[package]
name = "midi"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "rtmidi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.9.1"
midly = "0.5"

[build-dependencies]
cc = "*"
# bindgen = "*"
